name: GitHub Actions CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: app-dev
    steps:
      - name: Check code
        uses: actions/checkout@v3

      - name: Install dependency
        run: yarn
      - name: Build the Docker image
       runs:
        using: 'docker'
        image: 'app-dev'
        
