name: GitHub Actions CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
jobs:
  development:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - name: Check code
        uses: actions/checkout@v3

      - name: Install dependency
        run: yarn
      - name: Docker
        with:
          image: app-dev
          registry: docker.pkg.github.com
          dockerfile: Dockerfile
