name: Github actions CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  # When pushing to any branch then run this action
# Env variable
env:
  DOCKER_USER: tharinee35033
  DOCKER_PASSWORD: tharinee35033
  REPO_NAME: tharinee35033/docker-push-production
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - name: Check code
        uses: actions/checkout@v3

      - name: Install dependency
        run: yarn
