name: Github actions CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
env:
  DOCKER_USER: tharinee35033
  DOCKER_PASSWORD: tharinee35033
  REPO_NAME: tharinee35033/docker-push-production
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - name: Check code
        uses: actions/checkout@v3

      - name: Install dependency
        run: yarn
  push-image-to-docker-hub:
    needs:  pull-code
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2 
      - name: Pull code
        run: docker pull tharinee35033/docker-push-production:tagname
      - name: docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
      - name: Get current date 
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
      - name: Build the Docker image 
        run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:tagname
      - name: Docker Push
        run: docker push $DOCKER_USER/$REPO_NAME:tagname