name: GitHub Actions CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
jobs:
  build application in dev:
    runs-on: ubuntu-latest
    container: development
    steps:
      - name: Check code
        uses: actions/checkout@v3

      - name: Install dependency
        command: yarn

      - name: Build Application
        command: yarn start
      
      - name: Build the Docker image
        run:  docker build -t app-dev .

  build application in prod:
    runs-on: ubuntu-latest
    container: builder
    steps:
      - name: Check code
        uses: actions/checkout@v3

      - name: Install dependency
        command: yarn

      - name: Build Application
        command: yarn start
      
      - name: Build the Docker image
        run:  docker build -t app-prod .

